services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: cestajusta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cestajusta"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cestajusta-net

  app:
    build: .
    container_name: cestajusta-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cestajusta
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: 7WR/z7mNy/4SMGg0fmc5i79b5EX8BsTJGaAASswJUio=
    networks:
      - cestajusta-net

volumes:
  postgres_data:

networks:
  cestajusta-net:
    driver: bridge
