spring.datasource.url=jdbc:h2:mem:cestajusta;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret-base64=7WR/z7mNy/4SMGg0fmc5i79b5EX8BsTJGaAASswJUio=

server.port=8080

spring.sql.init.mode=never
