spring.datasource.url=jdbc:postgresql://localhost:5432/cestajusta
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret-base64=${JWT_SECRET:7WR/z7mNy/4SMGg0fmc5i79b5EX8BsTJGaAASswJUio=}

server.port=8080