spring.datasource.url=jdbc:postgresql://db:5432/cestajusta
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

jwt.secret-base64=${JWT_SECRET}


server.port=8080

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:cestajusta}
spring.rabbitmq.password=${RABBITMQ_PASS}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:cestajusta}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.template.mandatory=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

app.uploads.dir=${APP_UPLOADS_DIR:/data/uploads}
app.outbox.relay-delay-ms=${APP_OUTBOX_RELAY_DELAY_MS:45000}