spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/cestajusta}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:cestajusta}
spring.rabbitmq.password=${RABBITMQ_PASS}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST:cestajusta}

app.uploads.dir=${APP_UPLOADS_DIR:/data/uploads}